# Generated by Django 4.2.28 on 2026-02-07 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="shop_banners/"),
                ),
                ("latitude", models.FloatField(help_text="Latitude coordinate")),
                ("longitude", models.FloatField(help_text="Longitude coordinate")),
                ("is_verified", models.BooleanField(default=False)),
                ("is_accepting_orders", models.BooleanField(default=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("PRO", "Pro"),
                            ("BUSINESS", "Business"),
                        ],
                        default="STARTER",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("queue_capacity", models.PositiveIntegerField(default=10)),
                (
                    "operating_hours",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured operating hours"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override system commission rate",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PageRangeDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("min_pages", models.PositiveIntegerField()),
                ("max_pages", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_discounts",
                        to="stationary_shops.shop",
                    ),
                ),
            ],
            options={"ordering": ["min_pages"],},
        ),
        migrations.CreateModel(
            name="ShopPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("PRINTING_BW", "Black & White Printing"),
                            ("PRINTING_COLOR", "Color Printing"),
                            ("BINDING", "Binding"),
                            ("LAMINATION", "Lamination"),
                            ("SCANNING", "Scanning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modifiers", models.JSONField(blank=True, default=dict)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="stationary_shops.shop",
                    ),
                ),
            ],
            options={"unique_together": {("shop", "service_type")},},
        ),
    ]
