# Generated by Django 4.2.28 on 2026-03-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stationary_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number for communication', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional email for order confirmation', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Registered customer (null for guest orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_customer',
            field=models.ForeignKey(blank=True, help_text='Guest customer information (null for registered user orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stationary_orders.guestcustomer'),
        ),
    ]
