# Generated by Django 4.2.28 on 2026-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_orders', '0002_guestcustomer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('PAY_BEFORE', 'Pay Before Service'), ('PAY_AFTER', 'Pay After Service')], default='PAY_BEFORE', help_text='Payment preference', max_length=20),
        ),
    ]
