# Generated by Django 5.0 on 2026-03-09 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_orders', '0003_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('PAYMENT_FAILED', 'Payment Failed')], default='UNPAID', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTELMONEY', 'Airtel Money'), ('HALOPESA', 'Halopesa'), ('CARD', 'Card')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('clickpesa_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='stationary_orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
