# Generated by Django 4.2.28 on 2026-02-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stationary_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STUDENT", "Student"),
                    ("BUSINESS", "Business"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
    ]
